# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-linux-memory-tools" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "cb358fcf97f7346f5963b80f050c93115aaca3fe6c49e89cc48ad5b2cdcd2883"
      url "https://github.com/kevinpinscoe/aws-linux-memory-tools/releases/download/v#{version}/aws-linux-memory-tools-darwin-arm64"
      binary "aws-linux-memory-tools-darwin-arm64", target: "aws-linux-memory-tools"
    end
  end

  on_linux do
    on_intel do
      sha256 "27effed585bb8c52afa1387091e05cff0bc20dacd0aa13ee57fe3cff1863cdb5"
      url "https://github.com/kevinpinscoe/aws-linux-memory-tools/releases/download/v#{version}/aws-linux-memory-tools-linux-amd64"
      binary "aws-linux-memory-tools-linux-amd64", target: "aws-linux-memory-tools"
    end
    on_arm do
      sha256 "363dbd97cd627e4ba52d17ab67ea8747254e8ff6c34b82e04328f073ed3788dd"
      url "https://github.com/kevinpinscoe/aws-linux-memory-tools/releases/download/v#{version}/aws-linux-memory-tools-linux-arm64"
      binary "aws-linux-memory-tools-linux-arm64", target: "aws-linux-memory-tools"
    end
  end

  name "aws-linux-memory-tools"
  desc "AWS Linux memory diagnostics"
  homepage "https://github.com/kevinpinscoe/aws-linux-memory-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
