# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-linux-memory-tools" do
  version "1.0.3"

  on_macos do
    on_arm do
      sha256 "60d7930f7145f2f452d5f34c5061c8161fea06315ba8f881d1db44818c10caa9"
      url "https://github.com/kevinpinscoe/aws-linux-memory-tools/releases/download/v#{version}/aws-linux-memory-tools-darwin-arm64"
      binary "aws-linux-memory-tools-darwin-arm64", target: "aws-linux-memory-tools"
    end
  end

  on_linux do
    on_intel do
      sha256 "bb85fe6f31a6be72678d8cbd7b409939ac3cc011eed6d0bcd30ad14b0bfd75ac"
      url "https://github.com/kevinpinscoe/aws-linux-memory-tools/releases/download/v#{version}/aws-linux-memory-tools-linux-amd64"
      binary "aws-linux-memory-tools-linux-amd64", target: "aws-linux-memory-tools"
    end
    on_arm do
      sha256 "c7078f2a55e0175a1738b83dc324190e20fd09dae5955af4e66d1beae0fa8ec9"
      url "https://github.com/kevinpinscoe/aws-linux-memory-tools/releases/download/v#{version}/aws-linux-memory-tools-linux-arm64"
      binary "aws-linux-memory-tools-linux-arm64", target: "aws-linux-memory-tools"
    end
  end

  name "aws-linux-memory-tools"
  desc "AWS Linux memory diagnostics"
  homepage "https://github.com/kevinpinscoe/aws-linux-memory-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
