# This file was generated by .github/homebrew-cask.py. DO NOT EDIT.
cask "check-git-repos" do
  version "1.12.0"

  on_macos do
    on_arm do
      sha256 "1929b180951d5ebf6978ff6ede577513120f22901c1baa6d623c20aa44035eac"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-repos-v1.12.0/check-git-repos-darwin-arm64"
      binary "check-git-repos-darwin-arm64", target: "check-git-repos"
    end
  end

  on_linux do
    on_intel do
      sha256 "47317f8b5ae6acae1901a78d65ad07e5a8b1cb6dec6e1555c38b8346ba6663a9"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-repos-v1.12.0/check-git-repos-linux-amd64"
      binary "check-git-repos-linux-amd64", target: "check-git-repos"
    end
    on_arm do
      sha256 "de78630ec5233d9c72bf8f1965b0625809f66aed351319de471fd958a021e881"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-repos-v1.12.0/check-git-repos-linux-arm64"
      binary "check-git-repos-linux-arm64", target: "check-git-repos"
    end
  end

  name "check-git-repos"
  desc "Scan git repositories under a root directory for ahead/behind/diverged/uncommitted state"
  homepage "https://github.com/kevinpinscoe/tools"

  livecheck do
    skip "Auto-generated on release."
  end
end
