# This file was generated by .github/homebrew-cask.py. DO NOT EDIT.
cask "check-git-branch" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "d1a604a370acd6970e008c7bcb3ef3992ccef20c06cf836431ad166fea59e2ee"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-branch-v1.0.2/check-git-branch-darwin-arm64"
      binary "check-git-branch-darwin-arm64", target: "check-git-branch"
    end
  end

  on_linux do
    on_intel do
      sha256 "9a39de60a2fc8e120e4a33d76a0141713ea836348d3cd997f05ea774ddfa16d8"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-branch-v1.0.2/check-git-branch-linux-amd64"
      binary "check-git-branch-linux-amd64", target: "check-git-branch"
    end
    on_arm do
      sha256 "b0a2efb46adee07717be2d2e7d605d772444e9b890d93f8b7819e29287b90ca2"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-branch-v1.0.2/check-git-branch-linux-arm64"
      binary "check-git-branch-linux-arm64", target: "check-git-branch"
    end
  end

  name "check-git-branch"
  desc "Scan git repos for non-default branches or leftover local branches"
  homepage "https://github.com/kevinpinscoe/tools"

  livecheck do
    skip "Auto-generated on release."
  end
end
