# This file was generated by .github/homebrew-cask.py. DO NOT EDIT.
cask "check-git-branch" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "118142544c6928b1dacaf6159e6eaf6f5574c5b2048d00af831245d60d650b8b"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-branch-v2.0.0/check-git-branch-darwin-arm64"
      binary "check-git-branch-darwin-arm64", target: "check-git-branch"
    end
  end

  on_linux do
    on_intel do
      sha256 "a2d479e866cba1c29bf32113080a09ab794aeb12a648c5c8be6d918e470a9ab7"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-branch-v2.0.0/check-git-branch-linux-amd64"
      binary "check-git-branch-linux-amd64", target: "check-git-branch"
    end
    on_arm do
      sha256 "c024dc3187aca416fad5981f851da6a0ee7f2f5402ba18a948ffcd1181ac4710"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-branch-v2.0.0/check-git-branch-linux-arm64"
      binary "check-git-branch-linux-arm64", target: "check-git-branch"
    end
  end

  name "check-git-branch"
  desc "Scan git repos for non-default branches or leftover local branches"
  homepage "https://github.com/kevinpinscoe/tools"

  livecheck do
    skip "Auto-generated on release."
  end
end
