# This file was generated by .github/homebrew-cask.py. DO NOT EDIT.
cask "check-git-repos" do
  version "1.14.0"

  on_macos do
    on_arm do
      sha256 "75353319dfc6604219f56a5f687213c96c1ad6f809a97ba5ec42c11e97828a23"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-repos-v1.14.0/check-git-repos-darwin-arm64"
      binary "check-git-repos-darwin-arm64", target: "check-git-repos"
    end
  end

  on_linux do
    on_intel do
      sha256 "bb806588c29f7147deb5d77a014e32c0ad591231bde65ed81b4223b792d50c45"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-repos-v1.14.0/check-git-repos-linux-amd64"
      binary "check-git-repos-linux-amd64", target: "check-git-repos"
    end
    on_arm do
      sha256 "3cd774d1498ca9c5035ea709d2f521448d30357834b023784c3ae3124ac010ab"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-repos-v1.14.0/check-git-repos-linux-arm64"
      binary "check-git-repos-linux-arm64", target: "check-git-repos"
    end
  end

  name "check-git-repos"
  desc "Scan git repositories under a root directory for ahead/behind/diverged/uncommitted state"
  homepage "https://github.com/kevinpinscoe/tools"

  livecheck do
    skip "Auto-generated on release."
  end
end
