# This file was generated by .github/homebrew-cask.py. DO NOT EDIT.
cask "check-git-repos" do
  version "1.11.0"

  on_macos do
    on_arm do
      sha256 "6da803c96836cd4ec65ce66d350554bf9866d0186503da3b81fe3535109b2649"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-repos-v1.11.0/check-git-repos-darwin-arm64"
      binary "check-git-repos-darwin-arm64", target: "check-git-repos"
    end
  end

  on_linux do
    on_intel do
      sha256 "a96fa0f7e36b8cfe33e815030b50e93de901ae96866a499bc170f9a29048a4df"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-repos-v1.11.0/check-git-repos-linux-amd64"
      binary "check-git-repos-linux-amd64", target: "check-git-repos"
    end
    on_arm do
      sha256 "d3c24b98666e13963e24c612a34c957d64a60ccb535af7738e7f59f25f3c03c6"
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-repos-v1.11.0/check-git-repos-linux-arm64"
      binary "check-git-repos-linux-arm64", target: "check-git-repos"
    end
  end

  name "check-git-repos"
  desc "Scan git repositories under a root directory for ahead/behind/diverged/uncommitted state"
  homepage "https://github.com/kevinpinscoe/tools"

  livecheck do
    skip "Auto-generated on release."
  end
end
