# This file was generated by GoReleaser. DO NOT EDIT.
cask "get-wx" do
  version "1.0.3"

  on_macos do
    on_arm do
      sha256 "4dcc4171c2c9a6adf7771d7269299cdd6f5a490e5e4c3ac463d95ee218a6c1b0"
      url "https://github.com/kevinpinscoe/get-wx/releases/download/v#{version}/get-wx-darwin-arm64"
      binary "get-wx-darwin-arm64", target: "get-wx"
    end
  end

  on_linux do
    on_intel do
      sha256 "a6a8be6bc103a018711d6674c84cf13493b36a5a8f575d99d75c0c187af4b0b7"
      url "https://github.com/kevinpinscoe/get-wx/releases/download/v#{version}/get-wx-linux-amd64"
      binary "get-wx-linux-amd64", target: "get-wx"
    end
    on_arm do
      sha256 "d90a5a4ddb8618f4f9eea224859f8a6e9e05c769e7f2392b6243d714f9788891"
      url "https://github.com/kevinpinscoe/get-wx/releases/download/v#{version}/get-wx-linux-arm64"
      binary "get-wx-linux-arm64", target: "get-wx"
    end
  end

  name "get-wx"
  desc "Eastern Tennessee weather forecast fetcher"
  homepage "https://github.com/kevinpinscoe/get-wx"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
