# This file was generated by GoReleaser. DO NOT EDIT.
cask "get-wx" do
  version "1.0.4"

  on_macos do
    on_arm do
      sha256 "e130396d3347a689635177bfce045c7ee1181e12518b4a803be1cbb459505add"
      url "https://github.com/kevinpinscoe/get-wx/releases/download/v#{version}/get-wx-darwin-arm64"
      binary "get-wx-darwin-arm64", target: "get-wx"
    end
  end

  on_linux do
    on_intel do
      sha256 "cdc84cd62d69fc8221a8157b85269ff92e5fe231e242632f6097be4a7f4732d3"
      url "https://github.com/kevinpinscoe/get-wx/releases/download/v#{version}/get-wx-linux-amd64"
      binary "get-wx-linux-amd64", target: "get-wx"
    end
    on_arm do
      sha256 "20b741454fa3250ace3e683c71cb4871331110f3a82e7c09d21f983c1fca5e06"
      url "https://github.com/kevinpinscoe/get-wx/releases/download/v#{version}/get-wx-linux-arm64"
      binary "get-wx-linux-arm64", target: "get-wx"
    end
  end

  name "get-wx"
  desc "Eastern Tennessee weather forecast fetcher"
  homepage "https://github.com/kevinpinscoe/get-wx"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
