# This file was generated by .github/homebrew-cask.py. DO NOT EDIT.
cask "menu-app" do
  version "2.0.1"

  on_macos do
    on_arm do
      sha256 "e7c687e469c5ed03b410b5e5e012aae797b1905d383f93a641e097bfc8525bb7"
      url "https://github.com/kevinpinscoe/tools/releases/download/menu-app-v2.0.1/menu-app-darwin-arm64"
      binary "menu-app-darwin-arm64", target: "menu-app"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e4108bbc50bdfc6d86b2bfbbdc76a6aeb0cc2ec678a9446c5eaf505a31601ab"
      url "https://github.com/kevinpinscoe/tools/releases/download/menu-app-v2.0.1/menu-app-linux-amd64"
      binary "menu-app-linux-amd64", target: "menu-app"
    end
    on_arm do
      sha256 "1cd5a0f11584aee601ad1f62ab8da1733f9631298b73884c210f0249810584be"
      url "https://github.com/kevinpinscoe/tools/releases/download/menu-app-v2.0.1/menu-app-linux-arm64"
      binary "menu-app-linux-arm64", target: "menu-app"
    end
  end

  name "menu-app"
  desc "Run repository scripts from a simple TUI menu"
  homepage "https://github.com/kevinpinscoe/tools"

  livecheck do
    skip "Auto-generated on release."
  end
end
