# This file was generated by GoReleaser. DO NOT EDIT.
cask "metar-tool" do
  version "1.1.3"

  on_macos do
    on_arm do
      sha256 "5f5548386cc3c98653468ac6c302eb4ff68aee6a61bacc69e18f299e915c293e"
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v#{version}/metar-tool-darwin-arm64"
      binary "metar-tool-darwin-arm64", target: "metar-tool"
    end
  end

  on_linux do
    on_intel do
      sha256 "c64fccd86c2bc9a7cd958bf1b03d5b02cd69c32463a6f359a76879ad537842df"
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v#{version}/metar-tool-linux-amd64"
      binary "metar-tool-linux-amd64", target: "metar-tool"
    end
    on_arm do
      sha256 "74f8495aa2b2ca0216c88b9270e78c2cf2bc2f0ae6af4f6649cbb4fe77073eef"
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v#{version}/metar-tool-linux-arm64"
      binary "metar-tool-linux-arm64", target: "metar-tool"
    end
  end

  name "metar-tool"
  desc "METAR aviation weather decoder"
  homepage "https://github.com/kevinpinscoe/metar-tool"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
