# This file was generated by GoReleaser. DO NOT EDIT.
cask "metar-tool" do
  version "1.1.2"

  on_macos do
    on_arm do
      sha256 "33375bbf3c897c91ec80a9564ca30527d52a3da1346f2d391c7f9a4ccf8b75db"
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v#{version}/metar-tool-darwin-arm64"
      binary "metar-tool-darwin-arm64", target: "metar-tool"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4caabc999e6246571710ca4757071b1d5d7da8a8f1d2b4d014cfcbeff5b8c58"
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v#{version}/metar-tool-linux-amd64"
      binary "metar-tool-linux-amd64", target: "metar-tool"
    end
    on_arm do
      sha256 "0c2dd2546f2d035c9af1a1204a27b61d2d340cb76a5fe472017fcea9ea9d8284"
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v#{version}/metar-tool-linux-arm64"
      binary "metar-tool-linux-arm64", target: "metar-tool"
    end
  end

  name "metar-tool"
  desc "METAR aviation weather decoder"
  homepage "https://github.com/kevinpinscoe/metar-tool"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
