# This file was generated by GoReleaser. DO NOT EDIT.
cask "metar-tool" do
  version "1.1.4"

  on_macos do
    on_arm do
      sha256 "6c28407e54a8a6d1854a738b3f43b2d9ecfa25e1650056c7a27a22a564249172"
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v#{version}/metar-tool-darwin-arm64"
      binary "metar-tool-darwin-arm64", target: "metar-tool"
    end
  end

  on_linux do
    on_intel do
      sha256 "4d13e548f049450678d34cac1ceb1e71dd227938f8b8076785999f2d65c7ff70"
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v#{version}/metar-tool-linux-amd64"
      binary "metar-tool-linux-amd64", target: "metar-tool"
    end
    on_arm do
      sha256 "35681ffa53b1079f3e0ac43bc4f7750e1a7cfc491da85a0aaf600dd9a1b9eb60"
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v#{version}/metar-tool-linux-arm64"
      binary "metar-tool-linux-arm64", target: "metar-tool"
    end
  end

  name "metar-tool"
  desc "METAR aviation weather decoder"
  homepage "https://github.com/kevinpinscoe/metar-tool"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
