# This file was generated by GoReleaser. DO NOT EDIT.
cask "parzival" do
  version "0.1.0-pre.2"

  on_macos do
    on_arm do
      sha256 "6ec10760ed305bf8f250253f1bc656fffe009c8c7164c90bfe6b47859ec6a5ef"
      url "https://github.com/kevinpinscoe/parzival/releases/download/v#{version}/parzival-darwin-arm64"
      binary "parzival-darwin-arm64", target: "parzival"
    end
  end

  on_linux do
    on_intel do
      sha256 "a9b98070edff04aea261b915ea6177f98a1366d1743a4378156ee343f50a978f"
      url "https://github.com/kevinpinscoe/parzival/releases/download/v#{version}/parzival-linux-amd64"
      binary "parzival-linux-amd64", target: "parzival"
    end
    on_arm do
      sha256 "257916af63e997fe11d4c8ee7b1db4e48960fcfdf329607839bbbefcb874f55f"
      url "https://github.com/kevinpinscoe/parzival/releases/download/v#{version}/parzival-linux-arm64"
      binary "parzival-linux-arm64", target: "parzival"
    end
  end

  name "parzival"
  desc "Secret broker / credential-leak prevention system"
  homepage "https://github.com/kevinpinscoe/parzival"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
