# This file was generated by GoReleaser. DO NOT EDIT.
cask "parzival" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "80d2e75c7866a523bfe39949a7eaa0e1d71fe9ff2b0d9b7d0e584267a51ab2e0"
      url "https://github.com/kevinpinscoe/parzival/releases/download/v#{version}/parzival-darwin-arm64"
      binary "parzival-darwin-arm64", target: "parzival"
    end
  end

  on_linux do
    on_intel do
      sha256 "1fcdff4d48afb1d6dd202c1f9d5679e6993af63ebb4fbdb8c218f6b978b32f6e"
      url "https://github.com/kevinpinscoe/parzival/releases/download/v#{version}/parzival-linux-amd64"
      binary "parzival-linux-amd64", target: "parzival"
    end
    on_arm do
      sha256 "c49859a5a0799d139beb032ca730b41e332ebb88cef3ede8fa088572ac69e435"
      url "https://github.com/kevinpinscoe/parzival/releases/download/v#{version}/parzival-linux-arm64"
      binary "parzival-linux-arm64", target: "parzival"
    end
  end

  name "parzival"
  desc "Secret broker / credential-leak prevention system"
  homepage "https://github.com/kevinpinscoe/parzival"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
