# This file was generated by GoReleaser. DO NOT EDIT.
cask "parzival" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "a3bd61f34ab64c02a09365ef209c0dd24b020e7ab0818f50d37b497bd749b009"
      url "https://github.com/kevinpinscoe/parzival/releases/download/v#{version}/parzival-darwin-arm64"
      binary "parzival-darwin-arm64", target: "parzival"
    end
  end

  on_linux do
    on_intel do
      sha256 "8954370a9bb784e354d424517b3e02bd1be79d124f0dcefde64cda8793de5396"
      url "https://github.com/kevinpinscoe/parzival/releases/download/v#{version}/parzival-linux-amd64"
      binary "parzival-linux-amd64", target: "parzival"
    end
    on_arm do
      sha256 "d3148947f44a02127b89e721fb94e26f9f500b56167a1eac4757cb29ca420e65"
      url "https://github.com/kevinpinscoe/parzival/releases/download/v#{version}/parzival-linux-arm64"
      binary "parzival-linux-arm64", target: "parzival"
    end
  end

  name "parzival"
  desc "Secret broker / credential-leak prevention system"
  homepage "https://github.com/kevinpinscoe/parzival"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
