# This file was generated by .github/homebrew-cask.py. DO NOT EDIT.
cask "pause" do
  version "1.1.2"

  on_macos do
    on_arm do
      sha256 "d5236de2d3a30c23d4e4116fe4259ad66a6c32fe3e7e97f5ebf3988d70496084"
      url "https://github.com/kevinpinscoe/tools/releases/download/pause-v1.1.2/pause-darwin-arm64"
      binary "pause-darwin-arm64", target: "pause"
    end
  end

  on_linux do
    on_intel do
      sha256 "3668772efc52de5ecfa8b096451a8b0d82531c00d2697a5d8103acd1c923a1b9"
      url "https://github.com/kevinpinscoe/tools/releases/download/pause-v1.1.2/pause-linux-amd64"
      binary "pause-linux-amd64", target: "pause"
    end
    on_arm do
      sha256 "b6aec500dd4f644b7d62ccad1b71c1d7265fd8bd2297539f9b24a16b208f5c41"
      url "https://github.com/kevinpinscoe/tools/releases/download/pause-v1.1.2/pause-linux-arm64"
      binary "pause-linux-arm64", target: "pause"
    end
  end

  name "pause"
  desc "Sleep for N seconds with a live countdown status line on stderr"
  homepage "https://github.com/kevinpinscoe/tools"

  livecheck do
    skip "Auto-generated on release."
  end
end
