# This file was generated by GoReleaser. DO NOT EDIT.
cask "skills-tui" do
  version "3.0.2"

  on_macos do
    on_arm do
      sha256 "1a79ccdac0f39d315568b17cf19f72594f523dfd50b6b80676c2860345d53706"
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v#{version}/skills-darwin-arm64"
      binary "skills-darwin-arm64", target: "skills"
    end
  end

  on_linux do
    on_intel do
      sha256 "9933e5e13ce42287b1e82f94f83773b64859524a959dfb59b862f9e1d59096e1"
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v#{version}/skills-linux-amd64"
      binary "skills-linux-amd64", target: "skills"
    end
    on_arm do
      sha256 "97e9cbb2667c9ee70ec530a927fb4a3bf90018a8e0519e5c7605d8433c2d1345"
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v#{version}/skills-linux-arm64"
      binary "skills-linux-arm64", target: "skills"
    end
  end

  name "skills-tui"
  desc "Interactive TUI skill chooser"
  homepage "https://github.com/kevinpinscoe/skills-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
