# This file was generated by GoReleaser. DO NOT EDIT.
cask "skills-tui" do
  version "3.0.1"

  on_macos do
    on_arm do
      sha256 "e582963cbb1c961d922b2c9582518cae3fb992f22951ae3db7fb2ca060f20193"
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v#{version}/skills-darwin-arm64"
      binary "skills-darwin-arm64", target: "skills"
    end
  end

  on_linux do
    on_intel do
      sha256 "0d3635e21a458dc558cab889566b8d145a3f1e732fe4497426c3c5e290a2eb68"
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v#{version}/skills-linux-amd64"
      binary "skills-linux-amd64", target: "skills"
    end
    on_arm do
      sha256 "8f4f447f9a0b86f075eec2b69908d4ca2cc78c532ca85b636af35f466bcecc7f"
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v#{version}/skills-linux-arm64"
      binary "skills-linux-arm64", target: "skills"
    end
  end

  name "skills-tui"
  desc "Interactive TUI skill chooser"
  homepage "https://github.com/kevinpinscoe/skills-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
