# This file was generated by GoReleaser. DO NOT EDIT.
cask "skills-tui" do
  version "4.0.0"

  on_macos do
    on_arm do
      sha256 "cc225bbe76c14c0d727c35a66b8e3895e27624bf03c537b1a0e567173f4d07d1"
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v#{version}/skills-darwin-arm64"
      binary "skills-darwin-arm64", target: "skills"
    end
  end

  on_linux do
    on_intel do
      sha256 "3a2dfb33228955ab244d4fe1f126787d1c04ece6f221005986fd414f4061edc1"
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v#{version}/skills-linux-amd64"
      binary "skills-linux-amd64", target: "skills"
    end
    on_arm do
      sha256 "d718e6ce97784a6f850ed09575a374e9092599f561892dc454fda6007bf9917d"
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v#{version}/skills-linux-arm64"
      binary "skills-linux-arm64", target: "skills"
    end
  end

  name "skills-tui"
  desc "Interactive TUI skill chooser"
  homepage "https://github.com/kevinpinscoe/skills-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
