# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsLinuxMemoryTools < Formula
  desc "AWS Linux memory diagnostics"
  homepage "https://github.com/kevinpinscoe/aws-linux-memory-tools"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinpinscoe/aws-linux-memory-tools/releases/download/v1.0.0/aws-linux-memory-tools-darwin-arm64"
      sha256 "59fea5f317eea02e02b14fa9c5864f140649d069ecb0660ccd7c040c8b6090cb"

      define_method(:install) do
        bin.install "aws-linux-memory-tools-darwin-arm64" => "aws-linux-memory-tools"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/aws-linux-memory-tools/releases/download/v1.0.0/aws-linux-memory-tools-linux-amd64"
      sha256 "afe881975dc0a9d90a66e30ba08fa14dbc3d00f05df3413022cff120b3c91e16"
      define_method(:install) do
        bin.install "aws-linux-memory-tools-linux-amd64" => "aws-linux-memory-tools"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/aws-linux-memory-tools/releases/download/v1.0.0/aws-linux-memory-tools-linux-arm64"
      sha256 "979f68f12a4799519ce149fc20fd2cc8d36cc74039b370aa1bb085a011462fa8"
      define_method(:install) do
        bin.install "aws-linux-memory-tools-linux-arm64" => "aws-linux-memory-tools"
      end
    end
  end

  test do
    system "#{bin}/aws-linux-memory-tools", "--help"
  end
end
