# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CheckGitBranch < Formula
  desc "Check git branch status across repositories"
  homepage "https://github.com/kevinpinscoe/tools"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinpinscoe/tools/releases/download/v1.0.0/check-git-branch-darwin-arm64"
      sha256 "be4cfd911b254a8326f2a2d74c5769e3a315e7feaf51de5b3b60e0d4263ac436"

      define_method(:install) do
        bin.install "check-git-branch-darwin-arm64" => "check-git-branch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/tools/releases/download/v1.0.0/check-git-branch-linux-amd64"
      sha256 "d55793140795e7302100db6e9e6b58391b2ac23eb7d0b58f869799d82e28c508"
      define_method(:install) do
        bin.install "check-git-branch-linux-amd64" => "check-git-branch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/tools/releases/download/v1.0.0/check-git-branch-linux-arm64"
      sha256 "6cc8fc48cf1371eadadc1a87db639636f77834c72569651e9608dc9c0ac373c2"
      define_method(:install) do
        bin.install "check-git-branch-linux-arm64" => "check-git-branch"
      end
    end
  end

  test do
    system "#{bin}/check-git-branch", "--help"
  end
end
