# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CheckGitRepos < Formula
  desc "Check git repositories for uncommitted or unpushed changes"
  homepage "https://github.com/kevinpinscoe/tools"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinpinscoe/tools/releases/download/v1.0.0/check-git-repos-darwin-arm64"
      sha256 "e4549dce6d5e9cfa7d153ae8b346b3e1eaace07485f0f6b799b0fbb94a3fd41f"

      define_method(:install) do
        bin.install "check-git-repos-darwin-arm64" => "check-git-repos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/tools/releases/download/v1.0.0/check-git-repos-linux-amd64"
      sha256 "4a6f1568200ff5f7e2cbbd5f48c94db892c24cb54639da58b0ac9bf2004d02b7"
      define_method(:install) do
        bin.install "check-git-repos-linux-amd64" => "check-git-repos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/tools/releases/download/v1.0.0/check-git-repos-linux-arm64"
      sha256 "5532d9c597e065f3fbf50e4416bf8f2ccd6dfea70ffa14bafa9b5103d6cbc2b9"
      define_method(:install) do
        bin.install "check-git-repos-linux-arm64" => "check-git-repos"
      end
    end
  end

  test do
    system "#{bin}/check-git-repos", "--help"
  end
end
