# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CheckGitBranch < Formula
  desc "Check git branch status across repositories"
  homepage "https://github.com/kevinpinscoe/tools"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-branch-v1.0.1/check-git-branch-darwin-arm64"
      sha256 "ebb657bfd2e1d89e3efc26567847dec21b707444e9efe40054ffe384b8e9b591"

      define_method(:install) do
        bin.install "check-git-branch-darwin-arm64" => "check-git-branch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-branch-v1.0.1/check-git-branch-linux-amd64"
      sha256 "e8ab8fff20a672dfa62f5f7078ede122e70a16c543abfa02df0f453d52a14f8d"
      define_method(:install) do
        bin.install "check-git-branch-linux-amd64" => "check-git-branch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/tools/releases/download/check-git-branch-v1.0.1/check-git-branch-linux-arm64"
      sha256 "5c5201131e2985dee6a0002841cdf6c68115cc7faafc2ac1af3ba79a201a8a65"
      define_method(:install) do
        bin.install "check-git-branch-linux-arm64" => "check-git-branch"
      end
    end
  end

  test do
    system "#{bin}/check-git-branch", "--help"
  end
end
