# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GetWx < Formula
  desc "Eastern Tennessee weather forecast fetcher"
  homepage "https://github.com/kevinpinscoe/get-wx"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinpinscoe/get-wx/releases/download/v1.0.1/get-wx-darwin-arm64"
      sha256 "3007bd83c7ceb3ef0963855940536c29a6a4fe5a802f504d9ecd823d4306e430"

      define_method(:install) do
        bin.install "get-wx-darwin-arm64" => "get-wx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/get-wx/releases/download/v1.0.1/get-wx-linux-amd64"
      sha256 "e63bf402088b27d03bd0dc358efd57db6f2723ce05178fec04b2f420c7f08b77"
      define_method(:install) do
        bin.install "get-wx-linux-amd64" => "get-wx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/get-wx/releases/download/v1.0.1/get-wx-linux-arm64"
      sha256 "8e9577bb139ff82b241fef0828baa27f1e4bb2c8da250c1074d9f33245b45b7e"
      define_method(:install) do
        bin.install "get-wx-linux-arm64" => "get-wx"
      end
    end
  end

  test do
    system "#{bin}/get-wx", "--help"
  end
end
