# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetarTool < Formula
  desc "METAR aviation weather decoder"
  homepage "https://github.com/kevinpinscoe/metar-tool"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v1.0.1/metar-tool-darwin-arm64"
      sha256 "48fa537c6d53d0b547ae48f6572baca9d8d0fbd1392e054d2bfdf254cf71241c"

      define_method(:install) do
        bin.install "metar-tool-darwin-arm64" => "metar-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v1.0.1/metar-tool-linux-amd64"
      sha256 "ce97a21faa4721571e10f3d53d3ec5a6f21e73109c78f16d8225a081707158c6"
      define_method(:install) do
        bin.install "metar-tool-linux-amd64" => "metar-tool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v1.0.1/metar-tool-linux-arm64"
      sha256 "886d2811899a0cc9f83bfd7d933577d5f3c890ca472ddf0107cf6ecccbe29646"
      define_method(:install) do
        bin.install "metar-tool-linux-arm64" => "metar-tool"
      end
    end
  end

  test do
    system "#{bin}/metar-tool", "--help"
  end
end
