# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetarTool < Formula
  desc "METAR aviation weather decoder"
  homepage "https://github.com/kevinpinscoe/metar-tool"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v1.1.1/metar-tool-darwin-arm64"
      sha256 "a2285fd6d2d33d97d63a84d2425822390c8b0e362c0499231736003a69c0091b"

      define_method(:install) do
        bin.install "metar-tool-darwin-arm64" => "metar-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v1.1.1/metar-tool-linux-amd64"
      sha256 "67bf18dc601444654439de1a1809fe64fcd82e3690ecef7780e7c8f60dd3795c"
      define_method(:install) do
        bin.install "metar-tool-linux-amd64" => "metar-tool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v1.1.1/metar-tool-linux-arm64"
      sha256 "cb179d1384bcd96e182eb574eb02826110030b0dea2589e549f6a38001bf353d"
      define_method(:install) do
        bin.install "metar-tool-linux-arm64" => "metar-tool"
      end
    end
  end

  test do
    system "#{bin}/metar-tool", "--help"
  end
end
