# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetarTool < Formula
  desc "METAR aviation weather decoder"
  homepage "https://github.com/kevinpinscoe/metar-tool"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v1.1.0/metar-tool-darwin-arm64"
      sha256 "4626fd848a86851a8ec21dc6316bdcbd77f06d00d94bf81f92d1de83f71338c9"

      define_method(:install) do
        bin.install "metar-tool-darwin-arm64" => "metar-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v1.1.0/metar-tool-linux-amd64"
      sha256 "3d75ad8bea1a25dd486271ee3ad4fcae9aa49298d077db610d93b853d1f3702d"
      define_method(:install) do
        bin.install "metar-tool-linux-amd64" => "metar-tool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/metar-tool/releases/download/v1.1.0/metar-tool-linux-arm64"
      sha256 "bd36132df08f4ccbcc4a3e0a03eb1c1ce7192a010ed9466e0d05a8e2d06303e1"
      define_method(:install) do
        bin.install "metar-tool-linux-arm64" => "metar-tool"
      end
    end
  end

  test do
    system "#{bin}/metar-tool", "--help"
  end
end
