# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pause < Formula
  desc "Pause terminal output until a keypress"
  homepage "https://github.com/kevinpinscoe/tools"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinpinscoe/tools/releases/download/v1.0.0/pause-darwin-arm64"
      sha256 "978c304fca6ed11c98c9bde27b1e76f81df6cc84e148137909a020a9b56fb016"

      define_method(:install) do
        bin.install "pause-darwin-arm64" => "pause"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/tools/releases/download/v1.0.0/pause-linux-amd64"
      sha256 "f9e0f74a02b92539f948b8fbbb927855bd96e4953fbe614754947e94e673b12b"
      define_method(:install) do
        bin.install "pause-linux-amd64" => "pause"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/tools/releases/download/v1.0.0/pause-linux-arm64"
      sha256 "8b9654db0728a0e35fdfc2e53bf16c11ee03c778e9afbab83c88c714dbff656c"
      define_method(:install) do
        bin.install "pause-linux-arm64" => "pause"
      end
    end
  end

  test do
    system "#{bin}/pause", "--help"
  end
end
