# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkillsTui < Formula
  desc "Interactive TUI skill chooser"
  homepage "https://github.com/kevinpinscoe/skills-tui"
  version "3.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v3.0.0/skills-darwin-arm64"
      sha256 "affe2c2fd756ec0771085e2da96607d6e1322b857f24bb777c25ca760415e575"

      define_method(:install) do
        bin.install "skills-darwin-arm64" => "skills"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v3.0.0/skills-linux-amd64"
      sha256 "d131cbe2b61247e319462dc3a894b8bfc33d21faa999a1bc39c01cd9302d3db5"
      define_method(:install) do
        bin.install "skills-linux-amd64" => "skills"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v3.0.0/skills-linux-arm64"
      sha256 "4b881aaac8744e32d9de5d129210bf3420b92b3ce15a8d7b16141b51c07136e7"
      define_method(:install) do
        bin.install "skills-linux-arm64" => "skills"
      end
    end
  end

  test do
    system "#{bin}/skills", "--help"
  end
end
