# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkillsTui < Formula
  desc "Interactive TUI skill chooser"
  homepage "https://github.com/kevinpinscoe/skills-tui"
  version "2.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v2.5.1/skill-darwin-arm64"
      sha256 "709af61886872e6888d833c6652a85bc4e759708b1f0dddeea28f7eea605fde4"

      define_method(:install) do
        bin.install "skill-darwin-arm64" => "skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v2.5.1/skill-linux-amd64"
      sha256 "701d09cf6587550486f01e40365095d61cf1a5b265975bcd0b291790b11387df"
      define_method(:install) do
        bin.install "skill-linux-amd64" => "skill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinpinscoe/skills-tui/releases/download/v2.5.1/skill-linux-arm64"
      sha256 "97a3c2ce2796e2c3075369d4559672e8f4fa9c5d6429662648854ccec1821a7d"
      define_method(:install) do
        bin.install "skill-linux-arm64" => "skill"
      end
    end
  end

  test do
    system "#{bin}/skill", "--help"
  end
end
